
--
-- Insert Guest account
--

-- replace Password-algorithm with that declared as [PASSWORD_ENCRYPT] in 'include/config.php'
INSERT INTO Players SET
   ID=1,
   Handle='guest',
   Name='Guest',
   Password=SHA1('guest'),
   Registerdate=CURDATE() ;
INSERT INTO ConfigPages SET User_ID=1 ;
INSERT INTO ConfigBoard SET User_ID=1 ;
INSERT INTO UserQuota SET uid=1 ;


--
-- Initial data for table 'Clock'
--

INSERT INTO Clock SET ID=0 ;
INSERT INTO Clock SET ID=1 ;
INSERT INTO Clock SET ID=2 ;
INSERT INTO Clock SET ID=3 ;
INSERT INTO Clock SET ID=4 ;
INSERT INTO Clock SET ID=5 ;
INSERT INTO Clock SET ID=6 ;
INSERT INTO Clock SET ID=7 ;
INSERT INTO Clock SET ID=8 ;
INSERT INTO Clock SET ID=9 ;
INSERT INTO Clock SET ID=10 ;
INSERT INTO Clock SET ID=11 ;
INSERT INTO Clock SET ID=12 ;
INSERT INTO Clock SET ID=13 ;
INSERT INTO Clock SET ID=14 ;
INSERT INTO Clock SET ID=15 ;
INSERT INTO Clock SET ID=16 ;
INSERT INTO Clock SET ID=17 ;
INSERT INTO Clock SET ID=18 ;
INSERT INTO Clock SET ID=19 ;
INSERT INTO Clock SET ID=20 ;
INSERT INTO Clock SET ID=21 ;
INSERT INTO Clock SET ID=22 ;
INSERT INTO Clock SET ID=23 ;
INSERT INTO Clock SET ID=100 ;
INSERT INTO Clock SET ID=101 ;
INSERT INTO Clock SET ID=102 ;
INSERT INTO Clock SET ID=103 ;
INSERT INTO Clock SET ID=104 ;
INSERT INTO Clock SET ID=105 ;
INSERT INTO Clock SET ID=106 ;
INSERT INTO Clock SET ID=107 ;
INSERT INTO Clock SET ID=108 ;
INSERT INTO Clock SET ID=109 ;
INSERT INTO Clock SET ID=110 ;
INSERT INTO Clock SET ID=111 ;
INSERT INTO Clock SET ID=112 ;
INSERT INTO Clock SET ID=113 ;
INSERT INTO Clock SET ID=114 ;
INSERT INTO Clock SET ID=115 ;
INSERT INTO Clock SET ID=116 ;
INSERT INTO Clock SET ID=117 ;
INSERT INTO Clock SET ID=118 ;
INSERT INTO Clock SET ID=119 ;
INSERT INTO Clock SET ID=120 ;
INSERT INTO Clock SET ID=121 ;
INSERT INTO Clock SET ID=122 ;
INSERT INTO Clock SET ID=123 ;
INSERT INTO Clock SET ID=201,Lastchanged=0 ;
INSERT INTO Clock SET ID=202,Lastchanged=0 ;
INSERT INTO Clock SET ID=203,Lastchanged=0 ;
INSERT INTO Clock SET ID=204,Lastchanged=0 ;
INSERT INTO Clock SET ID=205,Lastchanged=0 ;
INSERT INTO Clock SET ID=206,Lastchanged=0 ;

